# Generated by Django 4.2.7 on 2023-11-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
