# Generated by Django 4.2.7 on 2023-12-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_delete_yahir_rename_user_id_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_people',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(default='hotel', max_length=50),
        ),
    ]
