# Generated by Django 4.2.7 on 2024-01-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_employee_rename_title_reservation_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
