# Generated by Django 4.2.7 on 2024-01-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability', models.BooleanField(default=True)),
                ('ingredients', models.TextField()),
                ('allergens', models.TextField(blank=True, null=True)),
                ('cuisine_type', models.CharField(max_length=50)),
                ('spice_level', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(default='default_iamge.jpg', upload_to='archivos/')),
            ],
        ),
    ]
