# Generated by Django 4.2.7 on 2024-01-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='archivos/'),
        ),
    ]
